"""add connection_mode to slicers

Revision ID: 5ca8377f1cb7
Revises: b5430b1dd73e
Create Date: 2026-09-12 20:52:57.900693

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ca8377f1cb7'
down_revision: str | None = 'b5430b1dd73e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slicers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_mode', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slicers', schema=None) as batch_op:
        batch_op.drop_column('connection_mode')

    # ### end Alembic commands ###
