"""swap scoped api key for xauth fields

Revision ID: 6f0953234308
Revises: c8f1b1a0edd9
Create Date: 2026-09-11 17:32:19.788230

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f0953234308"
down_revision: str | None = "c8f1b1a0edd9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uplynk_accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scoped_kid", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("scoped_sub", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("scoped_private_b64_encrypted", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("scoped_scp", sa.Text(), nullable=True))
        batch_op.drop_column("scoped_api_key_encrypted")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uplynk_accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scoped_api_key_encrypted", sa.TEXT(), nullable=True))
        batch_op.drop_column("scoped_scp")
        batch_op.drop_column("scoped_private_b64_encrypted")
        batch_op.drop_column("scoped_sub")
        batch_op.drop_column("scoped_kid")

    # ### end Alembic commands ###
