"""add is_manual flag to slicers

Revision ID: 7dc0a4899073
Revises: 6f0953234308
Create Date: 2026-09-11 20:42:06.481994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dc0a4899073"
down_revision: str | None = "6f0953234308"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slicers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_manual", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slicers", schema=None) as batch_op:
        batch_op.drop_column("is_manual")

    # ### end Alembic commands ###
