"""add thumb_url to slicers

Revision ID: 9a3f2c8e1d47
Revises: 5ca8377f1cb7
Create Date: 2026-09-23 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a3f2c8e1d47"
down_revision: str | None = "5ca8377f1cb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slicers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("thumb_url", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slicers", schema=None) as batch_op:
        batch_op.drop_column("thumb_url")

    # ### end Alembic commands ###
