"""add admin_events table

Revision ID: b5430b1dd73e
Revises: 7dc0a4899073
Create Date: 2026-09-11 21:07:07.132453

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5430b1dd73e"
down_revision: str | None = "7dc0a4899073"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admin_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admin_events_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_admin_events_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_admin_events_timestamp"), ["timestamp"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_admin_events_category"))
        batch_op.drop_index(batch_op.f("ix_admin_events_actor_id"))

    op.drop_table("admin_events")
    # ### end Alembic commands ###
