"""initial schema

Revision ID: c8f1b1a0edd9
Revises:
Create Date: 2026-09-11 06:25:53.534326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8f1b1a0edd9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uplynk_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("workspace_id", sa.String(length=100), nullable=False),
        sa.Column("legacy_api_key_encrypted", sa.Text(), nullable=False),
        sa.Column("scoped_api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "slicers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uplynk_account_id", sa.Integer(), nullable=False),
        sa.Column("slicer_id", sa.String(length=100), nullable=False),
        sa.Column("slicer_api_url", sa.String(length=500), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("protocol", sa.String(length=50), nullable=True),
        sa.Column("plugin_id", sa.String(length=100), nullable=True),
        sa.Column("plugin_version", sa.String(length=50), nullable=True),
        sa.Column("last_state", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["uplynk_account_id"], ["uplynk_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uplynk_account_id", "slicer_id", name="uq_account_slicer"),
    )
    with op.batch_alter_table("slicers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_slicers_slicer_id"), ["slicer_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_slicers_uplynk_account_id"), ["uplynk_account_id"], unique=False
        )

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("slicer_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_snippet", sa.Text(), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["slicer_id"], ["slicers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_slicer_id"), ["slicer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_timestamp"), ["timestamp"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_slicers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("slicer_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["slicer_id"], ["slicers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "slicer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_slicers")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_audit_events_slicer_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("slicers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_slicers_uplynk_account_id"))
        batch_op.drop_index(batch_op.f("ix_slicers_slicer_id"))

    op.drop_table("slicers")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("uplynk_accounts")
    # ### end Alembic commands ###
